// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SAFResult;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SAFCommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SAFCommonRoot : GPBRootObject
@end

#pragma mark - SAFResult

typedef GPB_ENUM(SAFResult_FieldNumber) {
  SAFResult_FieldNumber_Success = 1,
  SAFResult_FieldNumber_Code = 2,
  SAFResult_FieldNumber_Msg = 3,
  SAFResult_FieldNumber_Displaymsg = 4,
};

@interface SAFResult : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) int64_t code;

@property(nonatomic, readwrite) BOOL hasCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *displaymsg;
/** Test to see if @c displaymsg has been set. */
@property(nonatomic, readwrite) BOOL hasDisplaymsg;

@end

#pragma mark - SAFSimpleResponse

typedef GPB_ENUM(SAFSimpleResponse_FieldNumber) {
  SAFSimpleResponse_FieldNumber_Result = 1,
};

@interface SAFSimpleResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SAFResult *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@end

#pragma mark - SAFRedirectResponse

typedef GPB_ENUM(SAFRedirectResponse_FieldNumber) {
  SAFRedirectResponse_FieldNumber_Result = 1,
  SAFRedirectResponse_FieldNumber_RedirectURL = 2,
};

@interface SAFRedirectResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SAFResult *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@property(nonatomic, readwrite, copy, null_resettable) NSString *redirectURL;
/** Test to see if @c redirectURL has been set. */
@property(nonatomic, readwrite) BOOL hasRedirectURL;

@end

#pragma mark - SAFOperator

typedef GPB_ENUM(SAFOperator_FieldNumber) {
  SAFOperator_FieldNumber_Type = 1,
  SAFOperator_FieldNumber_Id_p = 2,
  SAFOperator_FieldNumber_Title = 3,
  SAFOperator_FieldNumber_Name = 4,
};

@interface SAFOperator : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;
/** Test to see if @c type has been set. */
@property(nonatomic, readwrite) BOOL hasType;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;
/** Test to see if @c title has been set. */
@property(nonatomic, readwrite) BOOL hasTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
